### ISSUE TITLE
No emvapi is included in this directory.

### ISSUE THREAD

**Issue by MhmRhm** [fujian-morefun/XPOS_G_SDK#1]
it seems that emvapi headers and libs are not included in XPOS_G_SDK directory. When compiling demo app, I encounter the following error:

/home/morefun/h9g/m90app/xpos-sdk-demo/../../m90app/xpos-sdk-demo/src/upay/upay_consum.c:6:53: fatal error: EntryPoint/lib_emvpub/inc/emv_interface.h: No such file or directory
 #include "EntryPoint/lib_emvpub/inc/emv_interface.h"
                                                     ^
compilation terminated.
make: *** [/home/morefun/h9g/m90app/xpos-sdk-demo/../../out/LINUX_320_240/obj//home/morefun/h9g/m90app/xpos-sdk-demo/../../m90app/xpos-sdk-demo/src/upay/upay_consum.o] Error 1

looking forward for the solution.

**Comment by braysonjohn148** [comment]
I am getting the same error. How did you solve it.

**Comment by MhmRhm** [comment]
Are you on debug branch?

**Comment by braysonjohn148** [comment]
No, should I use debug branch?

**Comment by braysonjohn148** [comment]
Seems to build successfully after using the debug branch. Thanks
